services:
  mc_vanilla_server:
    image: itzg/minecraft-server
    container_name: mc_vanilla_server
    tty: true
    stdin_open: true
    stop_grace_period: 240s
    env_file:
      - ./.env
    ports:
      - "25566:25565"
    environment:

      EULA: "TRUE"
      SERVER_NAME: CP Vanilla
      MOTD: CP MC Vanilla
      MODE: survival
      ALLOW_FLIGHT: true
      SPAWN_PROTECTION: 8
      LEVEL: world-2026
      ONLINE_MODE: true
      ENFORCE_WHITELIST: true
      PLAYER_IDLE_TIMEOUT: 0
      DIFFICULTY: normal
      WHITELIST: |
        Myrddraa1
        essn23
        sandpaper223
        CompViral
      OPS: |
        Myrddraa1
        essn23
        sandpaper223
        CompViral
      
      TZ: America/Toronto
      INIT_MEMORY: 3G
      MAX_MEMORY: 10G
      ENABLE_ROLLING_LOGS: true
      SNOOPER_ENABLED: false
      STOP_SERVER_ANNOUNCE_DELAY: 60
       

    volumes:
      - ./data:/data
      - ./downloads:/downloads
